content = input("Enter some text: ")
catch = content.replace("a", "4")
catch = catch.replace("b", "8")
catch = catch.replace("e", "3")
catch = catch.replace("l", "1")
catch = catch.replace("o", "0")
catch = catch.replace("s", "5")
catch = catch.replace("t", "7")
print(catch)
